core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home' ),
    # Pessoas
    path('pessoas/', views.lista_pessoas, name='lista_pessoas'),
    path('pessoa-novo/', views.pessoa_novo, name='pessoa-novo'),
    path('pessoa-update/<int:pk>', views.pessoa_update, name="pessoa_update"),
    path('pessoa-delete/<int:pk>', views.pessoa_delete, name="pessoa_delete"),

    # Veiculos
    path('veiculos/', views.lista_veiculos, name='lista_veiculos'),
    path('veiculo-novo/', views.veiculo_novo, name='veiculo_novo'),
    path('veiculo-update/<int:pk>', views.veiculo_update, name='veiculo_update'),
    path('veiculo-delete/<int:pk>', views.veiculo_delete, name='veiculo_delete'),

    # Movimento Rotativo
    path('mov-rotativos/', views.lista_movrotativos, name='lista_movrotativos'),
    path('movrotativo-novo/', views.movrotativo_novo, name='movrotativo_novo'),
    path('movrotativo-update/<int:pk>', views.movrotativo_update, name='movrotativo_update'),
    path('movrotativo-delete/<int:pk>', views.movrotativo_delete, name='movrotativo_delete'),

    # Mensalista
    path('mensalistas/', views.lista_mensalistas, name='lista_mensalistas'),
    path('mensalista-novo/', views.mensalista_novo, name='mensalista_novo'),
    path('mensalista-update/<int:pk>', views.mensalista_update, name='mensalista_update'),
    path('mensalista-delete/<int:pk>', views.mensalista_delete, name='mensalista_delete'),

    # Movimento Mensalista
    path('mov-mensalistas/', views.lista_movmensalistas, name='lista_movmensalistas'),
    path('mov-mensalista-novo/', views.movmesalista_novo, name='movmensalista_novo'),
    path('mov-mensalista-update/<int:pk>', views.movmensalista_update, name='movmensalista_update'),
    path('mov-mensalista-delete/<int:pk>', views.movmensalista_delete, name='movmensalista_delete'),

    # Gerar PDF/CSV
    path('create_pdf/', views.CreatePdf.as_view(), name='create_pdf'),
    path('create_csv/', views.CreateCSV.as_view(), name='create_csv'),
]

estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import include, path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.home, name="home"),
    path('contato/', views.contato, name="contato"),
    path('contato/<mensagem>', views.contato, name="contato"),
    path('save_contato/', views.save_contato, name="save_contato"),
    path('servico/', views.servico, name="servico"),
]

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from .mail import send_mail_template

class ContatoForm(forms.Form):
    nome = forms.CharField ()
    telefone = forms.CharField()
    email = forms.EmailField()
    assunto = forms.CharField(max_length=60)
    mensagem = forms.CharField(widget=forms.Textarea)

    def send_mail(self):
        subject = self.cleaned_data['assunto']
        context = {
            'nome': self.cleaned_data['nome'],
            'email': self.cleaned_data['email'],
            'telefone': self.cleaned_data['telefone'],
            'mensagem': self.cleaned_data['mensagem'],
        }
        message = f"Nome: {context['nome']}; e-mail: {context['email']}; Telefone: {context['telefone']}; mensagem: {context['mensagem']}  "
        from_email = settings.DEFAULT_FROM_EMAIL
        recepient_list = [settings.CONTACT_EMAIL]
        template_name = 'website/mail_template.html'

        # Send the mail
        send_mail_template(subject, template_name, context, recepient_list)
        
        

website/views.py
from django.shortcuts import render, redirect
from . import forms

def home(request):
    template_name = 'website/index.html'
    return render(request, template_name)

def contato(request):
    template_name = 'website/contato.html'
    form = forms.ContatoForm(request.POST or None)
    data = {'form':form}
    if 'mensagem' in request.session:
        data['mensagem'] = request.session.pop('mensagem')
    return render(request, template_name, data)


def servico(request):
    template_name = 'website/servico.html'
    return render(request, template_name)


def save_contato(request):
    form = forms.ContatoForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        request.session['mensagem'] = "Enviado com sucesso"
    else:
        request.session['mensagem'] = "Formulario inválido"
        return render(request, 'webstite/contato.html', {'form':form})

    return redirect('website:contato')

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <title>{% block title %}Home{% endblock %} | Estacionamento-garage</title>
</head>

<body>
    <div class="container">
        <div class="row no-margin">
            <div class="col-md-6" style="text-align: right; padding-top:6%; float:right;">
                <h1>Estacionamento - Parking </h1>
                <p>Deixe seu carro conosco</p>
            </div>
            <div class="col-md-6" style="text-align: center">
                <img src="{% static 'img/Parking_logo.png' %}" alt="Estacionamento Logo">
            </div>
        </div>
        <br><br>{% include 'website/menu.html' %} <br><br>
        {% block main %}{% endblock %}
        {% include 'website/footer.html' %}
    </div>
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

website/templates/website/contato.html
{% extends 'website/base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-lg-6">
        {% if mensagem %}
            <p>{{ mensagem }}</p>
        {% endif %}
            
        <form action="{% url 'website:save_contato' %}" method="post">
            {% csrf_token %}
            {{form.erros}}
            {{form | bootstrap}}
            <input type="reset" value="Limpar" class="btn btn-danger">
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
    <div class="col-lg-6">
        <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus ipsa alias beatae cum minima expedita,
            tenetur unde odio numquam, dolores vitae laudantium placeat veritatis eos quisquam ullam dolor, eligendi
            quod?Iure odio numquam quod optio sit consectetur voluptates distinctio quis ut, omnis ipsa fuga ratione
            odit consequuntur, aperiam accusamus rem. Mollitia provident ipsa nostrum ex quisquam magni voluptatibus,
            cum laboriosam!
        </p>
        <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15670931.312588584!2d-96.0213466!3d-16.4800454!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce899637113bfb%3A0x8f4ec560bdc6de4c!2sRua+Rafael+da+Silva+Santos+-+Bonsucesso%2C+Guarulhos+-+SP%2C+07179-167!5e0!3m2!1spt-BR!2sbr!4v1555544054199!5m2!1spt-BR!2sbr" width="500" height="359" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/footer.html
<div class="row no-margin-left">
    <div class="col-lg-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">Active</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
    </div>
    <div class="col-lg-9 ">
        <p class="footer-website"> &COPY; Copyright todos os direitos reservados </p>
    </div>
</div>

website/templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}

{% block main %}

<div class="row">
    <div class="col-lg-6">
        <section style="position: relative">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus quam perspiciatis voluptatum dolores
            labore, quibusdam nam sequi mollitia harum officiis iure, veritatis ducimus commodi exercitationem ullam
            praesentium eveniet debitis pariatur?Odit, laborum? Veritatis cupiditate numquam harum officiis veniam nihil
            nam esse, a dolor in culpa sit nobis illum fugit dolorum expedita. Sunt adipisci beatae atque recusandae
            officiis velit nulla tenetur!
            <br>
            <button class="btn btn-primary" style="left:5px; bottom:10px;">Ver Informações</button>
        </section>
    </div>
    <div class="col-lg-6">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate voluptatem, id sequi nisi at sunt illum
        reiciendis, unde sapiente ipsum deleniti distinctio delectus corrupti maxime odio. Ipsam assumenda vitae
        voluptatum.Totam sapiente reiciendis omnis ipsam eveniet ea, quas cumque aut, aliquam voluptatum accusantium
        enim quo eligendi? Dolorum expedita dolorem, vero magnam esse obcaecati assumenda voluptatem temporibus dicta
        voluptatibus? Dignissimos, omnis?
        <br><br>
        <button class="btn btn-primary"> Ver Informações</button>

    </div>
</div>

<div class="row">
    <div class="col-lg-4">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi voluptas nisi harum vel maiores odit culpa consequatur ex voluptates eos qui omnis, molestiae perferendis tempore, quis, ratione asperiores laboriosam quibusdam?Adipisci, in deleniti? Aliquam exercitationem ea eum iste tenetur fuga rerum molestiae sunt aut alias, cupiditate dolore asperiores provident fugiat minima! Quis fugit veritatis obcaecati soluta ipsum ad autem corporis.
        dolore! Ea libero praesentium necessitatibus possimus quibusdam commodi iure, minima incidunt nihil iste
    </div>
    <div class="col-lg-4" style="text-align: center">
        <img src="{% static 'img/Parking_logo.png' %}" alt="Estacionamento Logo">
    </div>
    <div class="col-lg-4">
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Natus non officia eius odit, dolorem
        id repudiandae sequi cum vel, iure minima incidunt veniam ipsam labore temporibus. Dolore officia aperiam
        dicta.Voluptatibus maxime at quisquam dolorum expedita quia veritatis quos laboriosam sint perferendis
        dignissimos, fuga necessitatibus nam quibusdam obcaecati. Incidunt quibusdam obcaecati deleniti officia sequi,
        pariatur recusandae praesentium eos nulla voluptatem.
    </div>
</div>

{% endblock %}

website/templates/website/mail_template.html
<p><strong>Nome: </strong>{{ nome }}</p>
<p><strong>Telefone: </strong>{{ telefone }}</p>
<p><strong>E-mail: </strong>{{ email }}</p>
<strong>Mensagem:</strong>{{ mensagem|linebreaks }}

website/templates/website/menu.html
<div class="row">
    <div class="col-lg-12">
        <nav class="nav nav-pills nav-fill">
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/' %}
                    active
                {% endif %}
                     " href="{% url 'website:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/servico/' %}
                    active
                {% endif %}
                    " href="{% url 'website:servico' %}">Serviços</a>
            </li>
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/sobre/' %}
                    active
                {% endif %}
                    " href="#">Sobre</a>
            </li>
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/planos/' %}
                    active
                {% endif %}
                    " href="#">Planos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/contato/' %}
                    active
                {% endif %}"
                 href="{% url 'website:contato' %}">Contato</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:home' %}">Sistema</a>
            </li>
        </nav>
    </div>
</div>

website/templates/website/servico.html
{% extends 'website/base.html' %}
{% load static %}

{% block main %}
<section>
    <div class="row">
        <div class="col-lg-12">
            <h1>Saiba mais sobre nossos serviços</h1>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga sapiente doloribus harum nostrum et. Ad
                modi
                reprehenderit ut itaque eligendi error, enim numquam quaerat! Vel iste excepturi eos cumque culpa itaque
                ducimus
                optio repellat, mollitia maiores placeat molestias eaque! Iste, labore fugit atque corrupti corporis,
                quod eligendi
                aspernatur, provident maiores autem quam. Assumenda neque amet, eos necessitatibus incidunt odio ipsam?
            </p>
        </div>

        <div class="col-lg-6">
            <img src="{% static 'img/Parking_logo.png' %}" alt="Estacionamento">
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/Parking_logo.png' %}" alt="Estacionamento">
        </div>
    </div>



</section>
{% endblock %}