core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home' ),
    # Pessoas
    path('pessoas/', views.lista_pessoas, name='lista_pessoas'),
    path('pessoa-novo/', views.pessoa_novo, name='pessoa-novo'),
    path('pessoa-update/<int:pk>', views.pessoa_update, name="pessoa_update"),
    path('pessoa-delete/<int:pk>', views.pessoa_delete, name="pessoa_delete"),

    # Veiculos
    path('veiculos/', views.lista_veiculos, name='lista_veiculos'),
    path('veiculo-novo/', views.veiculo_novo, name='veiculo_novo'),
    path('veiculo-update/<int:pk>', views.veiculo_update, name='veiculo_update'),
    path('veiculo-delete/<int:pk>', views.veiculo_delete, name='veiculo_delete'),

    # Movimento Rotativo
    path('mov-rotativos/', views.lista_movrotativos, name='lista_movrotativos'),
    path('movrotativo-novo/', views.movrotativo_novo, name='movrotativo_novo'),
    path('movrotativo-update/<int:pk>', views.movrotativo_update, name='movrotativo_update'),
    path('movrotativo-delete/<int:pk>', views.movrotativo_delete, name='movrotativo_delete'),

    # Mensalista
    path('mensalistas/', views.lista_mensalistas, name='lista_mensalistas'),
    path('mensalista-novo/', views.mensalista_novo, name='mensalista_novo'),
    path('mensalista-update/<int:pk>', views.mensalista_update, name='mensalista_update'),
    path('mensalista-delete/<int:pk>', views.mensalista_delete, name='mensalista_delete'),

    # Movimento Mensalista
    path('mov-mensalistas/', views.lista_movmensalistas, name='lista_movmensalistas'),
    path('mov-mensalista-novo/', views.movmesalista_novo, name='movmensalista_novo'),
    path('mov-mensalista-update/<int:pk>', views.movmensalista_update, name='movmensalista_update'),
    path('mov-mensalista-delete/<int:pk>', views.movmensalista_delete, name='movmensalista_delete'),

    # Gerar PDF/CSV
    path('create_pdf/', views.CreatePdf.as_view(), name='create_pdf'),
    path('create_csv/', views.CreateCSV.as_view(), name='create_csv'),
]

estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from math import ceil
from datetime import datetime
from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length=60)
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

class Marca(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Veiculo(models.Model):
    proprietario = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    modelo = models.CharField(max_length=60)
    placa = models.CharField(max_length=8)
    cor = models.CharField(max_length=20)
    observacoes = models.TextField('Observações', null=True, blank=True)

    def __str__(self):
        return self.modelo + ' '+ self.placa

class Parametros(models.Model):
    valor_hora = models.DecimalField(max_digits=5, decimal_places=2)
    valor_mes = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return "Todos paramentros"

class MovRotativo(models.Model):
    checkin = models.DateTimeField(auto_now=False)
    checkout = models.DateTimeField(auto_now=False, null=True, blank=True)
    valor_hora = models.DecimalField(max_digits=5, decimal_places=2)
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def hora_total(self):
        return ceil((self.checkout - self.checkin).total_seconds() / 3600)

    def total(self):
        return self.valor_hora * self.hora_total()

    def __str__(self):
        return self.veiculo.placa


class Mensalista(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    inicio = models.DateField()
    valor_mes = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return str(self.veiculo) + ' - ' + datetime.strftime(self.inicio, '%d/%m/%Y')

class MovMensalista(models.Model):
    mensalista = models.ForeignKey(Mensalista, on_delete=models.CASCADE)
    data_pagamento = models.DateField()
    total = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return str(self.mensalista) +' - '+ str(self.total)

core/forms.py
from django import forms
from . import models


class PessoaForm(forms.ModelForm):
    class Meta:
        model = models.Pessoa
        fields = ('__all__')


class VeiculoForm(forms.ModelForm):
    class Meta:
        fields = ('__all__')
        model = models.Veiculo


class MovRotativoForm(forms.ModelForm):
    class Meta:
        fields = ('__all__')
        model = models.MovRotativo



class MensalistaForm(forms.ModelForm):
    class Meta:
        fields = ('__all__')
        model = models.Mensalista



class MovMensalistaForm(forms.ModelForm):
    class Meta:
        fields = ('__all__')
        model = models.MovMensalista

core/views.py
from django.shortcuts import render, redirect
from . import models, forms
from django.views.generic.base import View
from django.contrib.auth.decorators import login_required
from xhtml2pdf import pisa
from django.template import Context
from django.http import HttpResponse
from django.template.loader import get_template
import csv
import io

@login_required
def home(request):
    template_name = 'core/index.html'
    return render(request, template_name)

@login_required
def lista_pessoas(request):
    pessoas = models.Pessoa.objects.all()
    form = forms.PessoaForm()
    data = {'pessoas':pessoas, 'form':form}
    return render(request, 'core/listar_pessoas.html', data)

@login_required
def pessoa_novo(request):
    form = forms.PessoaForm(request.POST or None)
    if form.is_valid():
        form.save()
    
    return redirect('core:lista_pessoas')

@login_required
def pessoa_update(request, pk):
    pessoa = models.Pessoa.objects.get(pk=pk)
    form = forms.PessoaForm(request.POST or None, instance=pessoa)
    data =  {'form':form, 'pessoa':pessoa}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:lista_pessoas')

    return render(request, 'core/pessoa_update.html', data)

@login_required
def pessoa_delete(request, pk):
    pessoa_delete = models.Pessoa.objects.get(pk=pk)
    data = {'obj':pessoa_delete}

    if request.method == 'POST':
        pessoa_delete.delete()
        return redirect('core:lista_pessoas')

    return render(request, 'core/confirm_delete.html', data)

@login_required
def lista_veiculos(request):
    veiculos = models.Veiculo.objects.all()
    form = forms.VeiculoForm()
    context = {'veiculos':veiculos, 'form':form}
    return render(request, 'core/listar_veiculos.html', context)

@login_required
def veiculo_novo(request):
    form = forms.VeiculoForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect('core:lista_veiculos')

@login_required
def veiculo_update(request, pk):
    veiculo = models.Veiculo.objects.get(id=pk)
    form = forms.VeiculoForm(request.POST or None, instance=veiculo)
    data = { 'form': form, 'veiculo':veiculo }

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:lista_veiculos')

    return render(request, 'core/veiculo_update.html', data)

@login_required
def veiculo_delete(request, pk):
    veiculo = models.Veiculo.objects.get(pk=pk)
    data = {'obj':veiculo}

    if request.method == 'POST':
        veiculo.delete()
        return redirect('core:lista_veiculos')

    return render(request, 'core/confirm_delete.html',data)

@login_required
def lista_movrotativos(request):
    mov_rots = models.MovRotativo.objects.all()
    form = forms.MovRotativoForm()
    context_data = {'mov_rots':mov_rots, 'form':form}
    return render(request, 'core/listar_mov_rot.html', context_data)

@login_required
def movrotativo_novo(request):
    form = forms.MovRotativoForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect('core:lista_movrotativos')

@login_required
def movrotativo_update(request, pk):
    mov_rotativo = models.MovRotativo.objects.get(pk=pk)
    form = forms.MovRotativoForm(request.POST or None, instance=mov_rotativo)
    data = {'form':form, 'mov_rotativo':mov_rotativo}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:lista_movrotativos')

    return render(request, 'core/movrotativo_update.html',data)

@login_required
def movrotativo_delete(request, pk):
    movrotativo = models.MovRotativo.objects.get(pk=pk)
    data = {'obj':movrotativo}

    if request.method == 'POST':
        movrotativo.delete()
        return redirect('core:lista_movrotativos')

    return render(request, 'core/confirm_delete.html', data)

@login_required
def lista_mensalistas(request):
    mesalistas = models.Mensalista.objects.all()
    form = forms.MensalistaForm()
    context_data = {'mensalistas':mesalistas, 'form': form}
    return render(request, 'core/lista-mensalistas.html', context_data)

@login_required
def mensalista_novo(request):
    form = forms.MensalistaForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect('core:lista_mensalistas')

@login_required
def mensalista_update(request, pk):
    mensalista = models.Mensalista.objects.get(pk=pk)
    form = forms.MensalistaForm(request.POST or None, instance=mensalista)
    data = {'form':form, 'mensalista':mensalista}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:lista_mensalistas')

    return render(request, 'core/mensalista_update.html',data)

@login_required
def mensalista_delete(request, pk):
    mensalista = models.Mensalista.objects.get(pk=pk)
    data = {'obj':mensalista}

    if request.method == 'POST':
        mensalista.delete()
        return redirect('core:lista_mensalistas')

    return render(request, 'core/confirm_delete.html', data)

@login_required
def lista_movmensalistas(request):
    mov_menslistas = models.MovMensalista.objects.all()
    form = forms.MovMensalistaForm()
    context_data = {'mov_mensalistas':mov_menslistas, 'form': form}
    return render(request, 'core/lista-movmensalistas.html', context_data)

@login_required
def movmesalista_novo(request):
    form = forms.MovMensalistaForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect('core:lista_mensalistas')

@login_required
def movmensalista_update(request, pk):
    movmensalista = models.MovMensalista.objects.get(pk=pk)
    form = forms.MovMensalistaForm(request.POST or None, instance=movmensalista)
    data = {'form':form, 'movmensalista':movmensalista}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:lista_movmensalistas')

    return render(request, 'core/movmensalista_update.html', data)

@login_required
def movmensalista_delete(request, pk):
    movmensalista = models.MovMensalista.objects.get(pk=pk)
    data = {'obj':movmensalista}

    if request.method == 'POST':
        movmensalista.delete()
        return redirect('core:lista_movmensalistas')

    return render(request, 'core/confirm_delete.html', data)

class Render:
    @staticmethod
    def render(template_name: str, params: dict, filename: str):
        template = get_template(template_name)
        html = template.render(params)
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment;filename={filename}.pdf'
        pdf = pisa.CreatePDF(html, dest=response)
        if not pdf.err:
            return response
        else:
            return HttpResponse('Error Rendering pdf', status=400)


class CreatePdf(View):
    def get(self, request):
        veiculos = models.Veiculo.objects.all()
        params = {
            'veiculos': veiculos,
            'request': request,
        }

        return Render.render('core/relatorio_pdf.html', params, 'relatorio_veiculos')

class CreateCSV(View):
    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachement;filename="arquivo.csv"'

        veiculos = models.Veiculo.objects.all()

        writer = csv.writer(response)
        writer.writerow(['Id','marca','modelo','placa','cor','proprietario','observacoes'])

        for veiculo in veiculos:
            writer.writerow(
                [veiculo.id, veiculo.marca, veiculo.modelo, veiculo.placa, 
                veiculo.cor, veiculo.proprietario, veiculo.observacoes]
            )

        return response

core/templates/core/confirm_delete.html
{% extends 'base.html' %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Tem certeza que deseja excluir <b>{{obj}}</b></h2>
        <form action="#" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default">Confirmar</button>
        </form>
    </div>
</div>
{% endblock main %}

{% block title %}
    Delete confim
{% endblock %}
    

core/templates/core/index.html
{% extends 'base.html' %}


{% block main %}
    <div class="row" style="margin: 10% 30%">
        <div class="col-md-12 offset-md-1">
            <h2>Seja bem Vindo! <strong>{{ user.first_name }}</strong></h2>
        </div>
    </div>
{% endblock %}

core/templates/core/lista-mensalistas.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Lista de Mensalistas</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'core:mensalista_novo' %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
    <div class="col-md-6">
        <table class="table table-light table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
            {% for mensalista in mensalistas %}
                <tr>
                    <td><a href="{% url 'core:mensalista_update' mensalista.id %}">{{ mensalista.veiculo.proprietario.nome}}</a></td>
                    <td><a href="{% url 'core:mensalista_delete' mensalista.id %}" class="btn btn-danger pull-right">Excuir</a></td>
                </tr>
            {% endfor %}        
            </tbody>
        </table>        
    </div>
</div>
{% endblock main %}

{% block title %}
    Mesalistas
{% endblock %}

core/templates/core/lista-movmensalistas.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-6">
            <h3>Cadastrar novo Movimento de mensalista</h3>
        <form action="{% url 'core:movmensalista_novo' %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
    <div class="col-md-6">
        <h3>Lista do Movimento dos Mensalistas</h3>
        <table class="table table-light table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Nome</th>
                    <th>Veiculo</th>
                    <th>Data Pagamento</th>
                    <th>Total</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for mov_mensalista in mov_mensalistas %}
                <tr>
                    <td>
                        <a href="{% url 'core:movmensalista_update' mov_mensalista.id %}">{{ mov_mensalista.mensalista.veiculo.proprietario.nome }}</a>
                    </td>
                    <td>{{ mov_mensalista.mensalista.veiculo.modelo}}</td>
                    <td>{{ mov_mensalista.data_pagamento}}</td>
                    <td>{{ mov_mensalista.total}}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'core:movmensalista_delete' mov_mensalista.id %} " class="btn btn-danger pull-right">Excluir</a></td>
                        </div>

                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock main %}

{% block title %}
    Movimento Mensalistas
{% endblock %}

core/templates/core/listar_mov_rot.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Lista de movimento rotativo</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'core:movrotativo_novo' %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
    <div class="col-md-5">
        
        <table class="table table-light table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Nome</th>
                    <th>Check-in</th>
                    <th>Check-out</th>
                    <th>Veiculo</th>
                    <th>Total</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for rotativo in mov_rots %}
                    <tr>
                        <td><a href="{% url 'core:movrotativo_update' rotativo.id %}"> {{rotativo}} </a></td>
                        <td>{{rotativo.checkin| date:'d/m/Y H:i:s'}}</td>
                        <td>{{rotativo.checkout|date:'d/m/Y H:i:s'}}</td>
                        <td>{{rotativo.veiculo.modelo}}</td>
                        <td>R$ {{rotativo.total}}</td>
                        <td><a href="{% url 'core:movrotativo_delete' rotativo.id %}" class="pull-right btn btn-danger" style="float:right">Excluir</a> </li></td>
                    </tr>
                 {% endfor %}
            </tbody>
        </table>

        
    </div>
</div>
{% endblock main %}


{% block title %}
    Movimento Mensalistas
{% endblock %}
    

core/templates/core/listar_pessoas.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>
            Lista de Pessoas
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'core:pessoa-novo' %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary " value="Cadastrar">
        </form>
    </div>
    <div class="col-md-6">
        <table class="table table-light table-hover">
            <thead class="thead-dark">
                <th>Nome</th>
                <th>Ação</th>
            </thead>
            <tbody>
                {% for pessoa in pessoas %}
                <tr>
                  <td><a href="{% url 'core:pessoa_update' pessoa.id %}"> {{pessoa.nome}} </a> </td>
                  <td> <a href="{% url 'core:pessoa_delete' pessoa.id %}" class="btn btn-danger pull-right">Deletar</a></li></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block title %}
    Pessoas
{% endblock %}

core/templates/core/listar_veiculos.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Lista de veiculos</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'core:veiculo_novo' %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
    <div class="col-md-6">
        <table class="table table-light table-hover">
            <thead class="thead-dark">
                <th>Nome</th>
                <th style="text-align: center">Açoes</th>
            </thead>
            <tbody>
                {% for veiculo in veiculos %}
                <tr>
                    <td>
                        <a href="{% url 'core:veiculo_update' veiculo.id %}">{{veiculo.modelo}}</a>
                    </td>
                    <td>
                        <a href="{% url 'core:veiculo_delete' veiculo.id %}" class="btn btn-danger pull-right">Excluir</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'core:create_pdf' %}" class="btn btn-info">Gerar PDF</a>
        <a href="{% url 'core:create_csv' %}" class="btn btn-warning">Gerar CSV</a>
    </div>
</div>
{% endblock main %}

{% block title %}
    Veiculos
{% endblock %}
    

core/templates/core/mensalista_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Atualizar Mensalista {{ mensalista.veiculo.proprietario.nome }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'core:mensalista_update' mensalista.id %}" method="post">
            {% csrf_token %}
            {{form | bootstrap }}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
</div>
{% endblock main %}


{% block title %}
    Atualizar Mensalista
{% endblock %}
    

core/templates/core/movmensalista_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Atualizar movimento do mensalista {{ movmensalista.veiculo.proprietario.nome }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'core:movmensalista_update' movmensalista.id %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}
            <input type="submit" class="btn btn-primary" value="Atualizar">
        </form>
    </div>
</div>
{% endblock main %}
{% block title %}
    Atualizar Moviemento Mensalista
{% endblock %}

core/templates/core/movrotativo_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Atualizar movimento rotativo relativo ao {{ mov_rotativo.veiculo.modelo }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'core:movrotativo_update' mov_rotativo.id %}" method="post">
            {% csrf_token %}
            {{form | bootstrap }}
            <input type="submit" class="btn btn-primary" value="Atualizar">
        </form>
    </div>
</div>
{% endblock main %}

{% block title %}
    Atualizar Movimento Rotativo
{% endblock %}

core/templates/core/pessoa_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Atualiazar {{pessoa.nome}}</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'core:pessoa_update' pessoa.id %}" method="post">
            {% csrf_token %}
            {{form | bootstrap}}

            <input type="submit" class="btn btn-primary" value="Atualizar">
        </form>
    </div>
</div>
{% endblock main %}

{% block title %}
    Atualizar Pessoas
{% endblock %}

core/templates/core/relatorio_pdf.html
<!DOCTYPE html>
<html lang="pt-bt">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <table class="table table-light" style="text-align: left">
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Placa</th>
                <th>Cor</th>
                <th>Proprietario</th>
                <th>Observações</th>
            </tr>
        </thead>
        <tbody>
            {% for veiculo in veiculos %}
            <tr>
                <td>{{ veiculo.marca }}</td>
                <td>{{ veiculo.modelo }}</td>
                <td>{{ veiculo.placa }}</td>
                <td>{{ veiculo.cor }}</td>
                <td>{{ veiculo.proprietario }}</td>
                <td>{{ veiculo.observacoes }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-3.4.0.min.js"
        integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/core/veiculo_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <h2>Atualizar veiulo {{ veiculo.modelo }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="{% url 'core:veiculo_update' veiculo.id%}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Atualizar">
        </form>
    </div>
</div>
{% endblock main %}

{% block title %}
    Atualizar Veiculos
{% endblock %}