core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home' ),
    # Pessoas
    path('pessoas/', views.lista_pessoas, name='lista_pessoas'),
    path('pessoa-novo/', views.pessoa_novo, name='pessoa-novo'),
    path('pessoa-update/<int:pk>', views.pessoa_update, name="pessoa_update"),
    path('pessoa-delete/<int:pk>', views.pessoa_delete, name="pessoa_delete"),

    # Veiculos
    path('veiculos/', views.lista_veiculos, name='lista_veiculos'),
    path('veiculo-novo/', views.veiculo_novo, name='veiculo_novo'),
    path('veiculo-update/<int:pk>', views.veiculo_update, name='veiculo_update'),
    path('veiculo-delete/<int:pk>', views.veiculo_delete, name='veiculo_delete'),

    # Movimento Rotativo
    path('mov-rotativos/', views.lista_movrotativos, name='lista_movrotativos'),
    path('movrotativo-novo/', views.movrotativo_novo, name='movrotativo_novo'),
    path('movrotativo-update/<int:pk>', views.movrotativo_update, name='movrotativo_update'),
    path('movrotativo-delete/<int:pk>', views.movrotativo_delete, name='movrotativo_delete'),

    # Mensalista
    path('mensalistas/', views.lista_mensalistas, name='lista_mensalistas'),
    path('mensalista-novo/', views.mensalista_novo, name='mensalista_novo'),
    path('mensalista-update/<int:pk>', views.mensalista_update, name='mensalista_update'),
    path('mensalista-delete/<int:pk>', views.mensalista_delete, name='mensalista_delete'),

    # Movimento Mensalista
    path('mov-mensalistas/', views.lista_movmensalistas, name='lista_movmensalistas'),
    path('mov-mensalista-novo/', views.movmesalista_novo, name='movmensalista_novo'),
    path('mov-mensalista-update/<int:pk>', views.movmensalista_update, name='movmensalista_update'),
    path('mov-mensalista-delete/<int:pk>', views.movmensalista_delete, name='movmensalista_delete'),

    # Gerar PDF/CSV
    path('create_pdf/', views.CreatePdf.as_view(), name='create_pdf'),
    path('create_csv/', views.CreateCSV.as_view(), name='create_csv'),
]

estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Home{% endblock %} | Estacionamento-garage</title>
</head>
<body>
        
    {% if user.is_authenticated %}            
        <nav class="nav justify-content-end">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:lista_pessoas' %}">Pessoas</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link active" href="{% url 'core:lista_mensalistas' %}">Mensalistas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:lista_veiculos' %}">Veiculos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:lista_movrotativos' %}">Movimentos Rotativos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:lista_movmensalistas' %}">Moviemntos Mensalistas</a>
            </li>
            <li class="nav-item"></li>
            {% if user.is_authenticated %}
            <a class="nav-link">{{user}}</a>

            <small><a class="nav-link" href="{% url 'logout' %}">Logout</a></small>

            {% else %}
            <a class="nav-link" href="/admin/login/?next=/sistema/pessoas/">Login</a>
            {% endif %}
            </li>   
        </nav>
        <br><br>

    {% endif %}
            
    <div class="container-fluid">
        {% block main %}
        {% endblock %}
    </div>


    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>